services:
  postgres:
    image: docker.io/postgres:${POSTGRES_VERSION_TAG}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA: /var/lib/postgresql/data
    # volumes:
    # - ./data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  pgadmin:
    image: docker.io/elestio/pgadmin:${PGADMIN_VERSION_TAG}
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5433
    ports:
    - 5433:5433
    # volumes:
    #   - ./servers.json:/pgadmin4/servers.json


networks:
  database-network:

  


