name: app build and deploy

on: 
  push:
    branches:
      - main
    paths: 
      - .github/workflows/app-deploy.yaml
      - "cmd/**"
      - "internal/**"
      - Dockerfile

defaults:
  run:
    working-directory: .

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/chechout@v4

      - name: "Authenticate to Google Cloud"
        id: auth_gcp
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.DEV_GCP_WORKLOAD_IDP }}"
          service_account: "${{ secrets.DEV_GCP_SERV_ACCOUNT }}"
          token_format: access_token
          access_token_lifetime: 300s

      - name: "Authenticate to Docker"
          id: auth_docker
          uses: docker/login-action@v3
          with:
            username: "oauth2accesstoken"
            password: "${{ steps.auth_gcp.outputs.access_token }}"
            registry: "${{ vars.REGISTRY }}"
      
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.REGISTRY }}/app:latest
          cache-from: type=gha
          cache-go: type=gha,mode=max

      - name: "Deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with: 
          services: app
          image: ${{ var.REGISTRY }}/app:latest
          region: ${{ var.REGIOIN }}
          flags: ""
          secrets: |-
            GCP_IAP_AUD=GCP_IAP_AUD:latest